### ISSUE TITLE
Guard against empty strings

### ISSUE THREAD

**Issue by simondel** [adamralph/liteguard#170]
Are there any plans to support a guard against empty/whitespace strings?

**Comment by adamralph** [comment]
@simondel thanks for raising this. There are no plans to support this type of check. LiteGuard is very much a reflection of my personal opinion, which is that a requirement to disallow empty strings is ultimately a business rule and should be encapsulated appropriately (an empty string is still a valid string) rather than "guarded against". There's more about my philosophy on this on the README.

**Comment by simondel** [comment]
Would you be open to a PR that adds this or would you prefer not to have that because it goes against the philosophy of the package?

**Comment by adamralph** [comment]
@simondel it's the latter I'm afraid. In fact, when C# 8.0 hits, with non-nullable reference types, I may consider retiring the library altogether, since I think [it will be redundant](https://github.com/adamralph/liteguard#no-business-rule-clauses).

To that end, I'm closing this as a `wontfix`. I hope you understand the reasoning.
